import MyDialog from "@/components/Modal";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Trello 2.0",
  description: "Generated by Decole Mills",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`{inter.className} `}>
        <MyDialog />
        {children}
      </body>
    </html>
  );
}
